UNITIES_DECODE = {
    'AMPOLA': 'ampola',
    'BALDE': 'balde',
    'BANDEJ': 'bandeja',
    'BARRA': 'barra',
    'BISNAG': 'bisnaga',
    'BLOCO': 'bloco',
    'BOBINA': 'bobina',
    'BOMBEAR': 'bombona',
    'CÁPSULAS': 'cápsula',
    'CARRINHO': 'cartela',
    'CENTO': 'cento',
    'CJ': 'conjunto',
    'CM': 'centímetro',
    'CM2': 'centrimetro quadrado',
    'CX': 'caixa',
    'CX2': 'caixa com 2 unidades',
    'CX3': 'caixa com 3 unidades',
    'CX5': 'caixa com 5 unidades',
    'CX10': 'caixa com 10 unidades',
    'CX15': 'caixa com 15 unidades',
    'CX20': 'caixa com 20 unidades',
    'CX25': 'caixa com 25 unidades',
    'CX50': 'caixa com 50 unidades',
    'CX100': 'caixa com 100 unidades',
    'DISP': 'exibição',
    'DUZIA': 'duzia',
    'EMBAL': 'embalagem',
    'FARDO': 'fardo',
    'FOLHA': 'folha',
    'FRASCO': 'frasco',
    'FR': 'frasco',
    'GALAO': 'galão',
    'GF': 'garrafa',
    'GRAMAS': 'gramas',
    'JOGO': 'jogo',
    'KG': 'quilograma',
    'KIT': 'kit',
    'LATA': 'lata',
    'LA': 'lata',
    'LITRO': 'litro',
    'M': 'metro',
    'M2': 'metro quadrado',
    'M3': 'metro cúbico',
    'MILHEI': 'milheiro',
    'ML': 'mililitro',
    'MWH': 'Megawatt hora',
    'PACOTE': 'pacote',
    'PALETE': 'palete',
    'PARES': 'pares',
    'PC': 'peça',
    'AMIGO': 'amigo',
    'K': 'quilate',
    'RESMA': 'resma',
    'ROLO': 'rolo',
    'SACO': 'saco',
    'SACOLA': 'sacola',
    'TAMBOR': 'tambor',
    'TANQUE': 'tanque',
    'TON': 'tonelada',
    'TUBO': 'tubo',
    'UNID': 'unidade',
    'VASIL': 'vasilhame',
    'VIDRO': 'vidro',
}